% generate_megapress2d_with_cache.m
%
% SPDX-FileCopyrightText: Copyright (C) 2025 Frank C Langbein <frank@langbein.org>, Cardiff University
% SPDX-License-Identifier: BSD-3-Clause
%
% Cache unbroadened MEGAPRESS 2D simulation and reuse to generate spectra
% for multiple linewidths by applying the same time-domain decay used in
% FID-A sim_readout (Lorentzian/Gaussian/Lorentz-Gauss). Physics is
% unchanged; only computation is reorganized.
%
% USAGE:
% generate_megapress2d_with_cache(sys, p, linewidths, m_name, omega, save_dir, cache_dir)
% generate_megapress2d_with_cache(sys, p, linewidths, m_name, omega, save_dir, cache_dir, basis_roots)
%
% INPUTS:
% - sys        : metabolite spin system (from spinSystems)
% - p          : parameter struct as used by SimMega2D (fields: Npts, sw, Bfield, taus, RF, grid, phases, etc.)
% - linewidths : vector of FWHM linewidths in Hz
% - m_name     : metabolite name (string) for file naming
% - omega      : MHz (gamma*B0/1e6) for file naming
% - save_dir   : directory to write EDITON/OFF outputs per linewidth
% - cache_dir  : directory to store/load unbroadened cache
% - basis_roots: (optional) char or cellstr of directories to search for the
%                unbroadened cache file (recursively). If not provided, the
%                script will read cfg.json and use path_basis/search_basis.
%
% OUTPUTS:
% - Writes FIDA2D_..._MEGAPRESS_EDITOFF/EDITON files for each linewidth in save_dir
%
% NOTE:
% - The unbroadened cache is generated by calling SimMega2D with linewidth=0 Hz
%   so that sim_readout applies no decay (t2 = Inf).

function generate_megapress2d_with_cache(sys, p, linewidths, m_name, omega, save_dir, cache_dir, basis_roots)

  if ~exist(save_dir, 'dir')
    mkdir(save_dir);
  end
  if ~exist(cache_dir, 'dir')
    mkdir(cache_dir);
  end

  gamma = 42577000; % Hz/T (FID-A convention)

  % Build cache key (basic; extend with hashes if needed)
  npts = p.Npts;
  sw   = p.sw;
  cache_name = sprintf('FIDA2D_UNBROAD_%s_%d_%d_%.2f.mat', m_name, sw, npts, omega);
  cache_path = fullfile(cache_dir, cache_name);

  % Load or create unbroadened cache (linewidth = 0 Hz)
  if exist(cache_path, 'file')
    S = load(cache_path, 't', 'ppm', 'ON_fids', 'OFF_fids', 'Bo');
    t        = S.t;
    ppm      = S.ppm;
    ON_fids  = S.ON_fids;
    OFF_fids = S.OFF_fids;
    Bo       = S.Bo;
  else
    % If not in cache_dir directly, search using basis paths as in Python cfg
    roots = {};
    % If provided by caller, use those roots
    if nargin >= 8 && ~isempty(basis_roots)
      if ischar(basis_roots)
        roots = { basis_roots };
      elseif isstring(basis_roots)
        roots = cellstr(basis_roots);
      elseif iscell(basis_roots)
        roots = basis_roots;
      end
    end
    % Otherwise derive from cfg.json in project root
    if isempty(roots)
      % Determine project root from this file location: .../mrsnet/simulators/fida -> project root
      this_file = mfilename('fullpath');
      [d1,~] = fileparts(this_file);      % .../fida
      [d2,~] = fileparts(d1);             % .../simulators
      [d3,~] = fileparts(d2);             % .../mrsnet
      [path_root,~] = fileparts(d3);      % project root

      % Load cfg.json if available
      cfg_file = fullfile(path_root, 'cfg.json');
      cfg = struct();
      if exist(cfg_file, 'file')
        try
          txt = fileread(cfg_file);
          cfg = jsondecode(txt);
        catch
          cfg = struct();
        end
      end

      % Resolve path_basis and search_basis similar to Python Cfg.init defaults
      default_path_basis = fullfile(path_root, 'data', 'basis');
      path_basis = default_path_basis;
      if isfield(cfg, 'path_basis') && ~isempty(cfg.path_basis)
        if ischar(cfg.path_basis)
          if isfolder(cfg.path_basis) && (startsWith(cfg.path_basis, filesep) || contains(cfg.path_basis, ':/'))
            path_basis = cfg.path_basis;
          else
            path_basis = fullfile(path_root, cfg.path_basis);
          end
        end
      end

      % search_basis list; default to basis-dist under data
      search_basis = { fullfile(path_root, 'data', 'basis-dist') };
      if isfield(cfg, 'search_basis') && ~isempty(cfg.search_basis)
        sb = cfg.search_basis;
        if ischar(sb)
          sb = { sb };
        end
        resolved = {};
        for ii = 1:numel(sb)
          pth = sb{ii};
          if startsWith(pth, filesep) || contains(pth, ':/')
            resolved{end+1} = pth; %#ok<AGROW>
          else
            resolved{end+1} = fullfile(path_root, pth); %#ok<AGROW>
          end
        end
        search_basis = resolved;
      end

      % Build unique list of roots to search
      roots = [{path_basis}, search_basis];
    end
    % Search recursively for the cache file
    alt_found = false;
    for rr = 1:numel(roots)
      root_dir = roots{rr};
      if exist(root_dir, 'dir')
        gp = genpath(root_dir);
        if ~isempty(gp)
          parts = strsplit(gp, pathsep);
          for kk = 1:numel(parts)
            if ~isempty(parts{kk})
              candidate = fullfile(parts{kk}, cache_name);
              if exist(candidate, 'file')
                cache_path = candidate;
                S = load(cache_path, 't', 'ppm', 'ON_fids', 'OFF_fids', 'Bo');
                t        = S.t;
                ppm      = S.ppm;
                ON_fids  = S.ON_fids;
                OFF_fids = S.OFF_fids;
                Bo       = S.Bo;
                alt_found = true;
                break;
              end
            end
          end
        end
      end
      if alt_found, break; end
    end
  end

  if ~exist('t', 'var')
    % Ensure linewidth=0 for unbroadened simulation
    p0 = p;
    p0.lw = 0.0;
    % Simulate once (no decay due to lw=0) with a unique temporary filename
    tmp_out = sprintf('temp_unbroadened_%s.mat', datestr(now, 'yyyymmdd_HHMMSS_FFF'));
    [ON, OFF, ~] = SimMega2D(sys, p0, tmp_out, cache_dir);
    % Collect required fields
    t        = OFF.t;
    ppm      = OFF.ppm;
    ON_fids  = ON.fids;
    OFF_fids = OFF.fids;
    Bo       = OFF.Bo;
    % Save cache
    save(cache_path, 't', 'ppm', 'ON_fids', 'OFF_fids', 'Bo', '-v7');
    % Clean up temporary file if created
    tmp_file_path = fullfile(cache_dir, tmp_out);
    if exist(tmp_file_path, 'file')
      try, delete(tmp_file_path); end
    end
  end

  % Apply lineshape per linewidth and write outputs
  % Use same formulas as FID-A sim_readout
  deltat = 1/sw;
  points = npts;
  l = 0:(points-1);
  pulse_sequence = 'megapress';

  for jj = 1:length(linewidths)
    lw = linewidths(jj);

    % Lorentzian broadening (default FID-A)
    t2 = Inf;
    if lw > 0
      t2 = 1/(pi*lw);
    end
    decay = exp(-((l)*deltat)/t2);

    % OFF
    edit = false;
    fid  = OFF_fids(:) .* decay(:); % force column vectors, avoid implicit expansion
    fft  = fftshift(ifft(fid));
    linewidth = lw;
    nu   = ppm;
    t    = t(:);
    f_name = sprintf('FIDA2D_%s_MEGAPRESS_EDITOFF_%.2f_%d_%d_%.2f.mat', m_name, lw, sw, npts, omega);
    save(fullfile(save_dir, f_name), 'm_name', 'nu', 'fid', 'fft', 'linewidth', 't', 'omega', 'edit', 'pulse_sequence');

    % ON
    edit = true;
    fid  = ON_fids(:) .* decay(:);
    fft  = fftshift(ifft(fid));
    linewidth = lw;
    nu   = ppm;
    t    = t(:);
    f_name = sprintf('FIDA2D_%s_MEGAPRESS_EDITON_%.2f_%d_%d_%.2f.mat', m_name, lw, sw, npts, omega);
    save(fullfile(save_dir, f_name), 'm_name', 'nu', 'fid', 'fft', 'linewidth', 't', 'omega', 'edit', 'pulse_sequence');
  end

end


