% generate_megapress2d_with_cache.m
%
% SPDX-FileCopyrightText: Copyright (C) 2025 Frank C Langbein <frank@langbein.org>, Cardiff University
% SPDX-License-Identifier: BSD-3-Clause
%
% Cache unbroadened MEGAPRESS 2D simulation and reuse to generate spectra
% for multiple linewidths by applying the same time-domain decay used in
% FID-A sim_readout (Lorentzian/Gaussian/Lorentz-Gauss). Physics is
% unchanged; only computation is reorganized.
%
% USAGE:
% generate_megapress2d_with_cache(sys, p, linewidths, m_name, omega, save_dir, cache_dir)
%
% INPUTS:
% - sys        : metabolite spin system (from spinSystems)
% - p          : parameter struct as used by SimMega2D (fields: Npts, sw, Bfield, taus, RF, grid, phases, etc.)
% - linewidths : vector of FWHM linewidths in Hz
% - m_name     : metabolite name (string) for file naming
% - omega      : MHz (gamma*B0/1e6) for file naming
% - save_dir   : directory to write EDITON/OFF outputs per linewidth
% - cache_dir  : directory to store/load unbroadened cache
%
% OUTPUTS:
% - Writes FIDA2D_..._MEGAPRESS_EDITOFF/EDITON files for each linewidth in save_dir
%
% NOTE:
% - The unbroadened cache is generated by calling SimMega2D with linewidth=0 Hz
%   so that sim_readout applies no decay (t2 = Inf).

function generate_megapress2d_with_cache(sys, p, linewidths, m_name, omega, save_dir, cache_dir)

  if ~exist(save_dir, 'dir')
    mkdir(save_dir);
  end
  if ~exist(cache_dir, 'dir')
    mkdir(cache_dir);
  end

  gamma = 42577000; % Hz/T (FID-A convention)

  % Build cache key (basic; extend with hashes if needed)
  npts = p.Npts;
  sw   = p.sw;
  cache_name = sprintf('FIDA2D_UNBROAD_%s_%d_%d_%.2f.mat', m_name, sw, npts, omega);
  cache_path = fullfile(cache_dir, cache_name);

  % Load or create unbroadened cache (linewidth = 0 Hz)
  if exist(cache_path, 'file')
    S = load(cache_path, 't', 'ppm', 'ON_fids', 'OFF_fids', 'Bo');
    t        = S.t;
    ppm      = S.ppm;
    ON_fids  = S.ON_fids;
    OFF_fids = S.OFF_fids;
    Bo       = S.Bo;
  else
    % Ensure linewidth=0 for unbroadened simulation
    p0 = p;
    p0.lw = 0.0;
    % Simulate once (no decay due to lw=0)
    [ON, OFF, ~] = SimMega2D(sys, p0, 'UNBROADED_TEMP.mat', cache_dir);
    % Collect required fields
    t        = OFF.t;
    ppm      = OFF.ppm;
    ON_fids  = ON.fids;
    OFF_fids = OFF.fids;
    Bo       = OFF.Bo;
    % Save cache
    save(cache_path, 't', 'ppm', 'ON_fids', 'OFF_fids', 'Bo', '-v7');
  end

  % Apply lineshape per linewidth and write outputs
  % Use same formulas as FID-A sim_readout
  deltat = 1/sw;
  points = npts;
  l = 0:(points-1);
  pulse_sequence = 'megapress';

  for jj = 1:length(linewidths)
    lw = linewidths(jj);

    % Lorentzian broadening (default FID-A)
    t2 = Inf;
    if lw > 0
      t2 = 1/(pi*lw);
    end
    decay = exp(-((l)*deltat)/t2);

    % OFF
    edit = false;
    fid  = (OFF_fids.').*decay.'; % ensure column shape
    fft  = fftshift(ifft(fid));
    linewidth = lw;
    nu   = ppm;
    tvec = t;
    f_name = sprintf('FIDA2D_%s_MEGAPRESS_EDITOFF_%.2f_%d_%d_%.2f.mat', m_name, lw, sw, npts, omega);
    save(fullfile(save_dir, f_name), 'm_name', 'nu', 'fid', 'fft', 'linewidth', 'tvec', 'omega', 'edit', 'pulse_sequence');

    % ON
    edit = true;
    fid  = (ON_fids.').*decay.';
    fft  = fftshift(ifft(fid));
    linewidth = lw;
    nu   = ppm;
    tvec = t;
    f_name = sprintf('FIDA2D_%s_MEGAPRESS_EDITON_%.2f_%d_%d_%.2f.mat', m_name, lw, sw, npts, omega);
    save(fullfile(save_dir, f_name), 'm_name', 'nu', 'fid', 'fft', 'linewidth', 'tvec', 'omega', 'edit', 'pulse_sequence');
  end

end


